"""DT-058 Sprint 2.1 — Scaffolder Java/Spring Boot.

Gera a estrutura inicial determinística de um projeto Spring Boot 3.x
com Java 21, Maven. Não chama LLM — todos os arquivos são gerados a
partir de `ScaffoldSpec`.

Layout produzido:
    pom.xml
    .gitignore
    README.md
    src/main/java/<package>/Application.java
    src/main/java/<package>/config/SecurityConfig.java     (se requires_security)
    src/main/resources/application.yml
    src/test/java/<package>/ApplicationTests.java

Decisões:
- Spring Boot 3.3.x (LTS-ish, Java 21 baseline) — pode ser sobrescrito
  via `framework_version`.
- Maven em vez de Gradle por compatibilidade ampla com clientes
  enterprise brasileiros (Maven domina o ecossistema bancário/jurídico
  no Brasil).
- `application.yml` em vez de `.properties` — sintaxe mais legível e
  amigável para configs hierárquicas.
- DataSource Postgres só se `database == "PostgreSQL"`. Para outros
  bancos, dependência fica fora do POM (LLM ou GP adiciona depois).
"""
from typing import List

from .types import ScaffoldFile, ScaffoldSpec


_SPRING_BOOT_DEFAULT_VERSION = "3.3.0"


def _package_to_path(package: str) -> str:
    """`com.acme.app` → `com/acme/app`."""
    return package.replace(".", "/")


def _class_name_from_slug(slug: str) -> str:
    """`automacao-juridica` → `AutomacaoJuridica` (PascalCase)."""
    parts = [p for p in slug.replace("_", "-").split("-") if p]
    return "".join(p[:1].upper() + p[1:].lower() for p in parts) or "Application"


def _pom_xml(spec: ScaffoldSpec) -> str:
    boot_version = spec.framework_version or _SPRING_BOOT_DEFAULT_VERSION

    deps_block_extra: List[str] = []
    if spec.requires_security:
        deps_block_extra.append(
            "        <dependency>\n"
            "            <groupId>org.springframework.boot</groupId>\n"
            "            <artifactId>spring-boot-starter-security</artifactId>\n"
            "        </dependency>"
        )
    if spec.requires_redis:
        deps_block_extra.append(
            "        <dependency>\n"
            "            <groupId>org.springframework.boot</groupId>\n"
            "            <artifactId>spring-boot-starter-data-redis</artifactId>\n"
            "        </dependency>"
        )
    if (spec.database or "").lower().startswith("postgres"):
        deps_block_extra.append(
            "        <dependency>\n"
            "            <groupId>org.postgresql</groupId>\n"
            "            <artifactId>postgresql</artifactId>\n"
            "            <scope>runtime</scope>\n"
            "        </dependency>\n"
            "        <dependency>\n"
            "            <groupId>org.springframework.boot</groupId>\n"
            "            <artifactId>spring-boot-starter-data-jpa</artifactId>\n"
            "        </dependency>"
        )

    extra_str = "\n".join(deps_block_extra)
    extra_block = f"\n{extra_str}\n" if extra_str else "\n"

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-gerado pelo GCA — não editar manualmente.
     Projeto: {spec.project_name}
     Stack: Java {spec.java_version} / Spring Boot {boot_version}
     [gca:auto] -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>{boot_version}</version>
        <relativePath/>
    </parent>

    <groupId>{spec.package}</groupId>
    <artifactId>{spec.project_slug}</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <name>{spec.project_name}</name>
    <description>Generated by GCA</description>

    <properties>
        <java.version>{spec.java_version}</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
{extra_block}
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""


def _application_java(spec: ScaffoldSpec) -> str:
    cls = _class_name_from_slug(spec.project_slug) + "Application"
    return f"""// Auto-gerado pelo GCA — não editar manualmente. [gca:auto]
package {spec.package};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class {cls} {{

    public static void main(String[] args) {{
        SpringApplication.run({cls}.class, args);
    }}
}}
"""


def _application_yml(spec: ScaffoldSpec) -> str:
    db_block = ""
    if (spec.database or "").lower().startswith("postgres"):
        db_block = (
            "  datasource:\n"
            "    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/app}\n"
            "    username: ${DATABASE_USER:app}\n"
            "    password: ${DATABASE_PASSWORD:changeme}\n"
            "    driver-class-name: org.postgresql.Driver\n"
            "  jpa:\n"
            "    hibernate:\n"
            "      ddl-auto: validate\n"
            "    show-sql: false\n"
        )

    redis_block = ""
    if spec.requires_redis:
        redis_block = (
            "  data:\n"
            "    redis:\n"
            "      host: ${REDIS_HOST:localhost}\n"
            "      port: ${REDIS_PORT:6379}\n"
        )

    return f"""# Auto-gerado pelo GCA — ajuste ENV e secrets via deploy. [gca:auto]
spring:
  application:
    name: {spec.project_slug}
{db_block}{redis_block}
server:
  port: ${{PORT:8080}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    {spec.package}: DEBUG
"""


def _security_config_java(spec: ScaffoldSpec) -> str:
    cls = _class_name_from_slug(spec.project_slug)
    return f"""// Auto-gerado pelo GCA — ajuste regras de autorização conforme RBAC do projeto. [gca:auto]
package {spec.package}.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;

@Configuration
public class {cls}SecurityConfig {{

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {{
        http
            .authorizeHttpRequests(auth -> auth
                .requestMatchers("/actuator/health", "/actuator/info").permitAll()
                .anyRequest().authenticated()
            )
            .httpBasic(basic -> {{}});
        return http;
    }}
}}
"""


def _application_tests_java(spec: ScaffoldSpec) -> str:
    cls = _class_name_from_slug(spec.project_slug) + "Application"
    return f"""// Auto-gerado pelo GCA — smoke test do contexto Spring. [gca:auto]
package {spec.package};

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class {cls}Tests {{

    @Test
    void contextLoads() {{
    }}
}}
"""


def _gitignore() -> str:
    return """# Auto-gerado pelo GCA. [gca:auto]
target/
!.mvn/wrapper/maven-wrapper.jar
!**/src/main/**/target/
!**/src/test/**/target/

### IDE ###
.idea/
*.iml
*.iws
*.ipr
.vscode/

### OS ###
.DS_Store
Thumbs.db

### Env ###
.env
.env.local
"""


def _readme(spec: ScaffoldSpec) -> str:
    return f"""# {spec.project_name}

> Scaffold inicial gerado pelo **GCA**. Edite normalmente — apenas
> arquivos com cabeçalho `[gca:auto]` podem ser sobrescritos em
> regenerações futuras.

## Stack

- Java {spec.java_version}
- Spring Boot {spec.framework_version or _SPRING_BOOT_DEFAULT_VERSION}
- Maven
{f"- {spec.database}" if spec.database else ""}
{"- Redis" if spec.requires_redis else ""}
{"- Spring Security (auth/RBAC)" if spec.requires_security else ""}

## Como rodar

```bash
./mvnw spring-boot:run
# ou
mvn spring-boot:run
```

A aplicação sobe em `http://localhost:8080`.
Health check: `http://localhost:8080/actuator/health`.

## Testes

```bash
./mvnw test
```

## Variáveis de ambiente

Veja `src/main/resources/application.yml` para os defaults. Configure
`DATABASE_URL`, `DATABASE_USER`, `DATABASE_PASSWORD`, `REDIS_HOST`,
etc no ambiente de execução.
"""


def scaffold_java_spring(spec: ScaffoldSpec) -> List[ScaffoldFile]:
    """Gera a estrutura inicial determinística de um projeto Spring Boot.

    Não chama LLM. Idempotente — chamar duas vezes com o mesmo `spec`
    produz a mesma lista de arquivos com o mesmo conteúdo.
    """
    pkg_path = _package_to_path(spec.package)
    files: List[ScaffoldFile] = [
        ScaffoldFile("pom.xml", _pom_xml(spec)),
        ScaffoldFile(".gitignore", _gitignore()),
        ScaffoldFile("README.md", _readme(spec)),
        ScaffoldFile(
            f"src/main/java/{pkg_path}/{_class_name_from_slug(spec.project_slug)}Application.java",
            _application_java(spec),
        ),
        ScaffoldFile(
            "src/main/resources/application.yml",
            _application_yml(spec),
        ),
        ScaffoldFile(
            f"src/test/java/{pkg_path}/{_class_name_from_slug(spec.project_slug)}ApplicationTests.java",
            _application_tests_java(spec),
        ),
    ]
    if spec.requires_security:
        files.append(
            ScaffoldFile(
                f"src/main/java/{pkg_path}/config/{_class_name_from_slug(spec.project_slug)}SecurityConfig.java",
                _security_config_java(spec),
            )
        )
    return files
